//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcZSGC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string PassWd { get; set; }
        public string Role { get; set; }
        public Nullable<int> Permission { get; set; }
        public string Mobile1 { get; set; }
        public string Imie { get; set; }
        public string Mobile2 { get; set; }
        public string Phone1 { get; set; }
        public string Sex { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Isuse { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string ReclassifyGroup { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string CLIENTID { get; set; }
        public string SpName { get; set; }
        public string SpPw { get; set; }
    }
}
